name: Build Orca Forks
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false # This prevents one failure from stopping the other build
      matrix:
        include:
          - fork_name: snapmaker-orca
            repo: "Snapmaker/OrcaSlicer"
            pattern: "Ubuntu2404.*AppImage"
            title: "Snapmaker Orca"
          - fork_name: fullspectrum-orca
            repo: "ratdoux/OrcaSlicer-FullSpectrum"
            pattern: "Ubuntu2404.*AppImage"
            title: "FullSpectrum Orca"

    steps:
      - uses: actions/checkout@v4
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v6 # Updated version
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.fork_name }}:latest
          build-args: |
            REPO=${{ matrix.repo }}
            PATTERN=${{ matrix.pattern }}
            TITLE=${{ matrix.title }}
